spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.80.133:3306/car
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      #最大连接池数量
      max-active: 100
      #初始连接池数量
      initial-size: 0
      # true非公平锁， 提高并发效率
      use-unfair-lock: true
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #最小连接池数量
      min-idle: 0
  redis:
    url: redis://192.168.80.128:6379
server:
  port: 15000